name: cdsodatacli-tests
channels:
  - conda-forge
dependencies:
  - ipython
  - pre-commit
  - pytest
  - pytest-reportlog
  - pytest-cov
  - numpy
  - toolz
  - cytoolz
  - python-dateutil
  - construct
  - geopandas
  - geodatasets
  - requests
  - shapely
  - tqdm
  - pyyaml
